name: 🍏 iOS Builds
on:
  workflow_call:

# Global Settings
env:
  SCONSFLAGS: verbose=yes warnings=extra werror=yes

jobs:
  ios:
    runs-on: "macos-latest"
    name: ${{ matrix.target }} ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        arch: [arm64]
        precision: [single, double]
        features: [simd-stable, enhanced-determinism]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build ${{ matrix.target }} ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          arch: ${{ matrix.arch }}
          platform: ios
          target: ${{ matrix.target }}
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}

      - name: Upload ${{ matrix.target }} ${{ matrix.arch }} ${{ matrix.precision }} ${{ matrix.features }}
        uses: ./.github/actions/upload
        with:
          precision: ${{ matrix.precision }}
          features: ${{ matrix.features }}
